version: '3.8'

services:
  db_reader:
    image: postgres:10.1-alpine
    container_name: reader_app_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - reader_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - proxynet

  php_apache_reader:
    container_name: reader_php_apache
    build:
      context: ./php
    ports:
      - ${HTTP_READER_PORT}:80
    volumes:
      - ./src:/var/www/rss_reader_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db_reader
    links:
      - ${DB_HOST}:db_reader
    networks:
      - proxynet

volumes:
  reader_postgres_data:

networks:
  proxynet:
    name: rss_network